python main.py --W_target_level 4
python main.py --W_target_level 5
python main.py --W_target_level 6
python main.py --W_target_level 7
python main.py --W_target_level 8
python main.py --W_target_level 9
python main.py --W_target_level 10
python main.py --W_target_level 11
python main.py --W_target_level 12
python main.py --W_target_level 13
python main.py --W_target_level 14
python main.py --W_target_level 15
python main.py --W_target_level 17
python main.py --W_target_level 18
python main.py --W_target_level 19
python main.py --W_target_level 20
python main.py --W_target_level 21
python main.py --W_target_level 22
python main.py --W_target_level 23
python main.py --W_target_level 24
python main.py --W_target_level 25
python main.py --W_target_level 26
python main.py --W_target_level 27
python main.py --W_target_level 28
python main.py --W_target_level 29
python main.py --W_target_level 30
python main.py --W_target_level 31
python main.py --W_target_level 32
python main.py --W_target_level 48
python main.py --W_target_level 56
python main.py --W_target_level 63
python main.py --W_target_level 64
python main.py --W_target_level 95
python main.py --W_target_level 96
python main.py --W_target_level 127
python main.py --W_target_level 128
python main.py --W_target_level 159
python main.py --W_target_level 160
python main.py --W_target_level 191
python main.py --W_target_level 192
python main.py --W_target_level 255
python main.py --W_target_level 256

